# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Panel.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AdminPanel(object):
    def setupUi(self, AdminPanel):
        AdminPanel.setObjectName(_fromUtf8("AdminPanel"))
        AdminPanel.resize(796, 534)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        AdminPanel.setFont(font)
        AdminPanel.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        AdminPanel.setWindowIcon(QtGui.QIcon('App_icon.png'))
        self.centralwidget = QtGui.QWidget(AdminPanel)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 331, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MV Boli"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.a_PlaceName = QtGui.QLineEdit(self.centralwidget)
        self.a_PlaceName.setGeometry(QtCore.QRect(200, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.a_PlaceName.setFont(font)
        self.a_PlaceName.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"border-style: groove;\n"
"border-width:1px;\n"
"border-color: rgb(255, 255, 255);"))
        self.a_PlaceName.setObjectName(_fromUtf8("a_PlaceName"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 310, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 171, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 380, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.a_hotelname = QtGui.QLineEdit(self.centralwidget)
        self.a_hotelname.setGeometry(QtCore.QRect(580, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.a_hotelname.setFont(font)
        self.a_hotelname.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"border-style: groove;\n"
"border-width:1px;\n"
"border-color: rgb(255, 255, 255);"))
        self.a_hotelname.setObjectName(_fromUtf8("a_hotelname"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 180, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 300, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.a_distance_type = QtGui.QComboBox(self.centralwidget)
        self.a_distance_type.setGeometry(QtCore.QRect(200, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_distance_type.setFont(font)
        self.a_distance_type.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.a_distance_type.setObjectName(_fromUtf8("a_distance_type"))
        self.a_distance_type.addItem(_fromUtf8(""))
        self.a_distance_type.addItem(_fromUtf8(""))
        self.a_budget = QtGui.QComboBox(self.centralwidget)
        self.a_budget.setGeometry(QtCore.QRect(200, 240, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_budget.setFont(font)
        self.a_budget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_budget.setObjectName(_fromUtf8("a_budget"))
        self.a_budget.addItem(_fromUtf8(""))
        self.a_budget.addItem(_fromUtf8(""))
        self.a_budget.addItem(_fromUtf8(""))
        self.a_budget.addItem(_fromUtf8(""))
        self.a_duration = QtGui.QComboBox(self.centralwidget)
        self.a_duration.setGeometry(QtCore.QRect(200, 310, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_duration.setFont(font)
        self.a_duration.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_duration.setObjectName(_fromUtf8("a_duration"))
        self.a_duration.addItem(_fromUtf8(""))
        self.a_duration.addItem(_fromUtf8(""))
        self.a_duration.addItem(_fromUtf8(""))
        self.a_season = QtGui.QComboBox(self.centralwidget)
        self.a_season.setGeometry(QtCore.QRect(20, 450, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_season.setFont(font)
        self.a_season.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_season.setObjectName(_fromUtf8("a_season"))
        self.a_season.addItem(_fromUtf8(""))
        self.a_season.addItem(_fromUtf8(""))
        self.a_season.addItem(_fromUtf8(""))
        self.a_distance4spot = QtGui.QComboBox(self.centralwidget)
        self.a_distance4spot.setGeometry(QtCore.QRect(620, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_distance4spot.setFont(font)
        self.a_distance4spot.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_distance4spot.setObjectName(_fromUtf8("a_distance4spot"))
        self.a_distance4spot.addItem(_fromUtf8(""))
        self.a_distance4spot.addItem(_fromUtf8(""))
        self.a_distance4spot.addItem(_fromUtf8(""))
        self.a_hotelrent = QtGui.QComboBox(self.centralwidget)
        self.a_hotelrent.setGeometry(QtCore.QRect(620, 300, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_hotelrent.setFont(font)
        self.a_hotelrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
""))
        self.a_hotelrent.setObjectName(_fromUtf8("a_hotelrent"))
        self.a_hotelrent.addItem(_fromUtf8(""))
        self.a_hotelrent.addItem(_fromUtf8(""))
        self.a_hotelrent.addItem(_fromUtf8(""))
        self.a_hotelrent.addItem(_fromUtf8(""))
        self.a_addButton = QtGui.QPushButton(self.centralwidget)
        self.a_addButton.setGeometry(QtCore.QRect(450, 430, 331, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_addButton.setFont(font)
        self.a_addButton.setStyleSheet(_fromUtf8("background-color: rgb(160, 160, 240);\n"
"color: rgb(0, 0, 0);"))
        self.a_addButton.setObjectName(_fromUtf8("a_addButton"))
        self.a_home = QtGui.QPushButton(self.centralwidget)
        self.a_home.setGeometry(QtCore.QRect(740, 0, 41, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a_home.setFont(font)
        self.a_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a_home.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.a_home.setObjectName(_fromUtf8("a_home"))
        self.a_on_off_season = QtGui.QComboBox(self.centralwidget)
        self.a_on_off_season.setGeometry(QtCore.QRect(200, 450, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_on_off_season.setFont(font)
        self.a_on_off_season.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_on_off_season.setObjectName(_fromUtf8("a_on_off_season"))
        self.a_on_off_season.addItem(_fromUtf8(""))
        self.a_on_off_season.addItem(_fromUtf8(""))
        self.a_hotel_security = QtGui.QComboBox(self.centralwidget)
        self.a_hotel_security.setGeometry(QtCore.QRect(200, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_hotel_security.setFont(font)
        self.a_hotel_security.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_hotel_security.setObjectName(_fromUtf8("a_hotel_security"))
        self.a_hotel_security.addItem(_fromUtf8(""))
        self.a_hotel_security.addItem(_fromUtf8(""))
        self.a_hotel_security.addItem(_fromUtf8(""))
        self.a_hotel_security.setItemText(2, _fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.a_comfortness = QtGui.QComboBox(self.centralwidget)
        self.a_comfortness.setGeometry(QtCore.QRect(620, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.a_comfortness.setFont(font)
        self.a_comfortness.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.a_comfortness.setObjectName(_fromUtf8("a_comfortness"))
        self.a_comfortness.addItem(_fromUtf8(""))
        self.a_comfortness.addItem(_fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(410, 110, 20, 381))
        self.frame.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"border-style: double;\n"
"border-width: 5px;\n"
"border-color: rgb(0, 85, 127);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(0, 10, 171, 81))
        self.label_51.setText(_fromUtf8(""))
        self.label_51.setPixmap(QtGui.QPixmap('logo.png'))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        AdminPanel.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(AdminPanel)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AdminPanel.setStatusBar(self.statusbar)

        self.retranslateUi(AdminPanel)
        QtCore.QMetaObject.connectSlotsByName(AdminPanel)

    def retranslateUi(self, AdminPanel):
        AdminPanel.setWindowTitle(_translate("AdminPanel", "Admin_Panel", None))
        self.label_2.setText(_translate("AdminPanel", "2.1", None))
        self.label.setText(_translate("AdminPanel", "Travel Fellow", None))
        self.label_3.setText(_translate("AdminPanel", "Place Name", None))
        self.label_7.setText(_translate("AdminPanel", "Tour Duration", None))
        self.label_8.setText(_translate("AdminPanel", "Approximate Budget", None))
        self.label_9.setText(_translate("AdminPanel", "Distance Type", None))
        self.label_4.setText(_translate("AdminPanel", "Security Level", None))
        self.label_5.setText(_translate("AdminPanel", "Hotel Name", None))
        self.label_10.setText(_translate("AdminPanel", "Distance from spot", None))
        self.label_11.setText(_translate("AdminPanel", "Hotel Rent", None))
        self.a_distance_type.setItemText(0, _translate("AdminPanel", "Near", None))
        self.a_distance_type.setItemText(1, _translate("AdminPanel", "Far", None))
        self.a_budget.setItemText(0, _translate("AdminPanel", "<5000", None))
        self.a_budget.setItemText(1, _translate("AdminPanel", "5000 - 8000", None))
        self.a_budget.setItemText(2, _translate("AdminPanel", "8000 - 12000", None))
        self.a_budget.setItemText(3, _translate("AdminPanel", "12000+", None))
        self.a_duration.setItemText(0, _translate("AdminPanel", "2-3 Days", None))
        self.a_duration.setItemText(1, _translate("AdminPanel", "3-4 Days", None))
        self.a_duration.setItemText(2, _translate("AdminPanel", "4-5 Days", None))
        self.a_season.setItemText(0, _translate("AdminPanel", "Summer", None))
        self.a_season.setItemText(1, _translate("AdminPanel", "Winter", None))
        self.a_season.setItemText(2, _translate("AdminPanel", "Spring", None))
        self.a_distance4spot.setItemText(0, _translate("AdminPanel", "Very Near", None))
        self.a_distance4spot.setItemText(1, _translate("AdminPanel", "Near", None))
        self.a_distance4spot.setItemText(2, _translate("AdminPanel", "Far", None))
        self.a_hotelrent.setItemText(0, _translate("AdminPanel", "<1000", None))
        self.a_hotelrent.setItemText(1, _translate("AdminPanel", "1000-2000", None))
        self.a_hotelrent.setItemText(2, _translate("AdminPanel", "2000-3000", None))
        self.a_hotelrent.setItemText(3, _translate("AdminPanel", "3000+", None))
        self.a_addButton.setText(_translate("AdminPanel", "Add As New Data", None))
        self.a_home.setText(_translate("AdminPanel", "H", None))
        self.a_on_off_season.setItemText(0, _translate("AdminPanel", "On Season", None))
        self.a_on_off_season.setItemText(1, _translate("AdminPanel", "Off Season", None))
        self.a_hotel_security.setItemText(0, _translate("AdminPanel", "Satisfction", None))
        self.a_hotel_security.setItemText(1, _translate("AdminPanel", "Perfect", None))
        self.label_6.setText(_translate("AdminPanel", "Comfortness", None))
        self.a_comfortness.setItemText(0, _translate("AdminPanel", "Luxury", None))
        self.a_comfortness.setItemText(1, _translate("AdminPanel", "Medium", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    AdminPanel = QtGui.QMainWindow()
    ui = Ui_AdminPanel()
    ui.setupUi(AdminPanel)
    AdminPanel.show()
    sys.exit(app.exec_())

